// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DeviceServiceClient is the client API for DeviceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceServiceClient interface {
	GetDataTypeBydID(ctx context.Context, in *Didmsg, opts ...grpc.CallOption) (*DataTypemsg, error)
}

type deviceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceServiceClient(cc grpc.ClientConnInterface) DeviceServiceClient {
	return &deviceServiceClient{cc}
}

func (c *deviceServiceClient) GetDataTypeBydID(ctx context.Context, in *Didmsg, opts ...grpc.CallOption) (*DataTypemsg, error) {
	out := new(DataTypemsg)
	err := c.cc.Invoke(ctx, "/devicepb.DeviceService/GetDataTypeBydID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceServiceServer is the server API for DeviceService service.
// All implementations must embed UnimplementedDeviceServiceServer
// for forward compatibility
type DeviceServiceServer interface {
	GetDataTypeBydID(context.Context, *Didmsg) (*DataTypemsg, error)
	mustEmbedUnimplementedDeviceServiceServer()
}

// UnimplementedDeviceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDeviceServiceServer struct {
}

func (UnimplementedDeviceServiceServer) GetDataTypeBydID(context.Context, *Didmsg) (*DataTypemsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataTypeBydID not implemented")
}
func (UnimplementedDeviceServiceServer) mustEmbedUnimplementedDeviceServiceServer() {}

// UnsafeDeviceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceServiceServer will
// result in compilation errors.
type UnsafeDeviceServiceServer interface {
	mustEmbedUnimplementedDeviceServiceServer()
}

func RegisterDeviceServiceServer(s grpc.ServiceRegistrar, srv DeviceServiceServer) {
	s.RegisterService(&DeviceService_ServiceDesc, srv)
}

func _DeviceService_GetDataTypeBydID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Didmsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).GetDataTypeBydID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devicepb.DeviceService/GetDataTypeBydID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).GetDataTypeBydID(ctx, req.(*Didmsg))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceService_ServiceDesc is the grpc.ServiceDesc for DeviceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devicepb.DeviceService",
	HandlerType: (*DeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDataTypeBydID",
			Handler:    _DeviceService_GetDataTypeBydID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

// TokenGuideClient is the client API for TokenGuide service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenGuideClient interface {
	GetUidByToken(ctx context.Context, in *Tokenmsg, opts ...grpc.CallOption) (*UserIDmsg, error)
	GetdIDByToken(ctx context.Context, in *Tokenmsg, opts ...grpc.CallOption) (*DeviceIDsmsg, error)
}

type tokenGuideClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenGuideClient(cc grpc.ClientConnInterface) TokenGuideClient {
	return &tokenGuideClient{cc}
}

func (c *tokenGuideClient) GetUidByToken(ctx context.Context, in *Tokenmsg, opts ...grpc.CallOption) (*UserIDmsg, error) {
	out := new(UserIDmsg)
	err := c.cc.Invoke(ctx, "/devicepb.TokenGuide/GetUidByToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenGuideClient) GetdIDByToken(ctx context.Context, in *Tokenmsg, opts ...grpc.CallOption) (*DeviceIDsmsg, error) {
	out := new(DeviceIDsmsg)
	err := c.cc.Invoke(ctx, "/devicepb.TokenGuide/GetdIDByToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenGuideServer is the server API for TokenGuide service.
// All implementations must embed UnimplementedTokenGuideServer
// for forward compatibility
type TokenGuideServer interface {
	GetUidByToken(context.Context, *Tokenmsg) (*UserIDmsg, error)
	GetdIDByToken(context.Context, *Tokenmsg) (*DeviceIDsmsg, error)
	mustEmbedUnimplementedTokenGuideServer()
}

// UnimplementedTokenGuideServer must be embedded to have forward compatible implementations.
type UnimplementedTokenGuideServer struct {
}

func (UnimplementedTokenGuideServer) GetUidByToken(context.Context, *Tokenmsg) (*UserIDmsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUidByToken not implemented")
}
func (UnimplementedTokenGuideServer) GetdIDByToken(context.Context, *Tokenmsg) (*DeviceIDsmsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetdIDByToken not implemented")
}
func (UnimplementedTokenGuideServer) mustEmbedUnimplementedTokenGuideServer() {}

// UnsafeTokenGuideServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenGuideServer will
// result in compilation errors.
type UnsafeTokenGuideServer interface {
	mustEmbedUnimplementedTokenGuideServer()
}

func RegisterTokenGuideServer(s grpc.ServiceRegistrar, srv TokenGuideServer) {
	s.RegisterService(&TokenGuide_ServiceDesc, srv)
}

func _TokenGuide_GetUidByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tokenmsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenGuideServer).GetUidByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devicepb.TokenGuide/GetUidByToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenGuideServer).GetUidByToken(ctx, req.(*Tokenmsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenGuide_GetdIDByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tokenmsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenGuideServer).GetdIDByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devicepb.TokenGuide/GetdIDByToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenGuideServer).GetdIDByToken(ctx, req.(*Tokenmsg))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenGuide_ServiceDesc is the grpc.ServiceDesc for TokenGuide service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenGuide_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devicepb.TokenGuide",
	HandlerType: (*TokenGuideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUidByToken",
			Handler:    _TokenGuide_GetUidByToken_Handler,
		},
		{
			MethodName: "GetdIDByToken",
			Handler:    _TokenGuide_GetdIDByToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
