// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TokenGuideClient is the client API for TokenGuide service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenGuideClient interface {
	GetToken(ctx context.Context, in *Tokenmsg, opts ...grpc.CallOption) (*UserIDmsg, error)
}

type tokenGuideClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenGuideClient(cc grpc.ClientConnInterface) TokenGuideClient {
	return &tokenGuideClient{cc}
}

func (c *tokenGuideClient) GetToken(ctx context.Context, in *Tokenmsg, opts ...grpc.CallOption) (*UserIDmsg, error) {
	out := new(UserIDmsg)
	err := c.cc.Invoke(ctx, "/pb.TokenGuide/GetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenGuideServer is the server API for TokenGuide service.
// All implementations must embed UnimplementedTokenGuideServer
// for forward compatibility
type TokenGuideServer interface {
	GetToken(context.Context, *Tokenmsg) (*UserIDmsg, error)
	mustEmbedUnimplementedTokenGuideServer()
}

// UnimplementedTokenGuideServer must be embedded to have forward compatible implementations.
type UnimplementedTokenGuideServer struct {
}

func (UnimplementedTokenGuideServer) GetToken(context.Context, *Tokenmsg) (*UserIDmsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToken not implemented")
}
func (UnimplementedTokenGuideServer) mustEmbedUnimplementedTokenGuideServer() {}

// UnsafeTokenGuideServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenGuideServer will
// result in compilation errors.
type UnsafeTokenGuideServer interface {
	mustEmbedUnimplementedTokenGuideServer()
}

func RegisterTokenGuideServer(s grpc.ServiceRegistrar, srv TokenGuideServer) {
	s.RegisterService(&TokenGuide_ServiceDesc, srv)
}

func _TokenGuide_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tokenmsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenGuideServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TokenGuide/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenGuideServer).GetToken(ctx, req.(*Tokenmsg))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenGuide_ServiceDesc is the grpc.ServiceDesc for TokenGuide service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenGuide_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TokenGuide",
	HandlerType: (*TokenGuideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetToken",
			Handler:    _TokenGuide_GetToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "token.proto",
}
